version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
            - node-cache-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint Code
          command: npm run lint
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Test Project
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test